#!/bin/bash

# Start a new tmux session in detached mode
tmux new-session -d

# Split the window vertically into two panes
tmux split-window -h

# Split the left pane horizontally into three
tmux select-pane -t 0
tmux send-keys 'python3 -m labrador.app.app' C-m
tmux split-window -v
tmux select-pane -t 0
tmux send-keys 'python3 -m labrador.app.dedicated' C-m
tmux split-window -v

# Split the right pane horizontally into two and run nvtop and htop
tmux select-pane -t 3
tmux send-keys 'htop' C-m
tmux split-window -v
tmux send-keys 'nvtop' C-m

# Attach to the tmux session
tmux attach-session

